#######################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################

spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:sybase://db:5000/testdb
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    username: sa
    password: myPassword
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 20

  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.SybaseDialect
    show-sql: false
